Repository ONSdigital/srm-rh-ui, pull requests merged in 2024-01, with the labels that each got.

#24 1316 Pass secret key through base config, use non default session name
  Dockerfile
  Makefile
  config.py
  rh_ui/app_setup.py
  whitelist.py
Labels: patch

#25 1316 Update url config for consistency
  config.py
  rh_ui/controllers/rh_service.py
Labels: bug, patch

#27 updating flask dependencies
  Pipfile.lock
Labels: patch, dependencies

#19 Upgrade to python 3.11
  .github/workflows/checks-and-tests.yml
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: patch

#28 Update version of label checker and exclude patch updates from Depend…
  .github/dependabot.yml
  .github/workflows/check-labels.yml
Labels: patch
